#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CONFIG = ROOT / "unity" / "tools" / "release" / "release_packages.json"
PACKAGES_ROOT = ROOT / "unity" / "packages"
OUTPUT = ROOT / "doc" / "release-audit.md"


def load_config():
    return json.loads(CONFIG.read_text())


def scan_text_file(path: Path, forbidden_patterns: dict[str, str]):
    hits = []
    text = path.read_text(encoding="utf-8")
    for label, pattern in forbidden_patterns.items():
        if pattern in text:
            for index, line in enumerate(text.splitlines(), start=1):
                if pattern in line:
                    hits.append((label, index, line.strip()))
    return hits


def main():
    config = load_config()
    lines = ["# Release Audit", "", "Generated by `unity/tools/release/release_audit.py`.", ""]
    failures: list[str] = []
    required_manifest_keys = ("name", "displayName", "version", "unity", "description", "author")
    required_readme_sections = (
        "## Installation",
        "## Quick start",
        "## API overview",
        "## Demo",
        "## Validation",
    )

    allowed_extensions = set(config["allowed_extensions"])
    forbidden_patterns = config["forbidden_patterns"]

    for entry in config["sellable_packages"]:
        name = entry["name"]
        package_dir = PACKAGES_ROOT / name
        lines.append(f"## `{name}`")

        if not package_dir.exists():
            failures.append(f"missing package directory: {name}")
            lines.append("- missing package directory")
            lines.append("")
            continue

        required_paths = list(config["required_paths"]) + list(entry.get("required_paths", []))
        missing = [required for required in required_paths if not (package_dir / required).exists()]
        if missing:
            failures.append(f"{name}: missing required paths: {', '.join(missing)}")
            lines.append(f"- missing required paths: {', '.join(missing)}")
        else:
            lines.append("- required paths present")

        manifest = json.loads((package_dir / "package.json").read_text(encoding="utf-8"))
        missing_manifest_keys = [key for key in required_manifest_keys if key not in manifest]
        if missing_manifest_keys:
            failures.append(f"{name}: package.json missing keys: {', '.join(missing_manifest_keys)}")
            lines.append(f"- package.json missing keys: {', '.join(missing_manifest_keys)}")
        else:
            lines.append("- package.json contains required release metadata keys")

        readme_text = (package_dir / "README.md").read_text(encoding="utf-8")
        missing_readme_sections = [section for section in required_readme_sections if section not in readme_text]
        if missing_readme_sections:
            failures.append(f"{name}: README missing sections: {', '.join(missing_readme_sections)}")
            lines.append(f"- README missing sections: {', '.join(missing_readme_sections)}")
        else:
            lines.append("- README contains required external-user sections")

        illegal_files = []
        forbidden_hits = []
        tracked_files = []
        for path in sorted(package_dir.rglob("*")):
            if path.is_dir():
                continue
            tracked_files.append(path.relative_to(ROOT))
            if path.suffix and path.suffix not in allowed_extensions:
                illegal_files.append(path.relative_to(ROOT))
            elif not path.suffix and path.name not in {"package.json", ".gitignore"}:
                illegal_files.append(path.relative_to(ROOT))

            if path.suffix in {".cs", ".md", ".json", ".asmdef", ".txt"} or path.name in {"package.json", ".gitignore"}:
                forbidden_hits.extend((path.relative_to(ROOT), *hit) for hit in scan_text_file(path, forbidden_patterns))

        if illegal_files:
            failures.append(f"{name}: non-whitelisted file types present")
            lines.append("- non-whitelisted files:")
            for path in illegal_files:
                lines.append(f"  - `{path}`")
        else:
            lines.append("- file types are release-safe")

        if forbidden_hits:
            failures.append(f"{name}: forbidden references present")
            lines.append("- forbidden references:")
            for path, label, line_number, snippet in forbidden_hits:
                lines.append(f"  - {label}: `{path}:{line_number}` `{snippet}`")
        else:
            lines.append("- no forbidden references found")

        lines.append("- packaged files:")
        for path in tracked_files:
            lines.append(f"  - `{path}`")
        lines.append("")

    if failures:
        lines.append("## Result")
        lines.append("- FAILED")
        lines.extend(f"- {failure}" for failure in failures)
    else:
        lines.append("## Result")
        lines.append("- PASSED")
        lines.append("- sellable packages contain only whitelisted files")
        lines.append("- sellable packages contain no forbidden architectural references")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT}")
    if failures:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
