import assert from 'node:assert/strict';
import {initializePhysics,GameCore,SETTINGS as S} from './physics-core.js';
await initializePhysics();
const settle=g=>{for(let i=0;i<120;i++)g.step();};
const g=new GameCore();settle(g);assert.ok(g.grounded(),'ground collision must exist');assert.ok(Math.abs(g.state().player.y-(S.playerRadius+S.playerHalfHeight))<.05,'feet should be on ground');
assert.equal(g.command({type:'Move',direction:3}),false,'invalid move must be rejected');assert.equal(g.command({type:'Invalid'}),false,'unknown commands must fail');
g.command({type:'Jump'});let highest=-Infinity;for(let i=0;i<160;i++){g.step();highest=Math.max(highest,g.state().player.y);}const peak=highest-S.playerRadius-S.playerHalfHeight;assert.ok(peak>.95&&peak<1.3,`jump must stay near human scale; got ${peak}m`);assert.equal(g.events.filter(e=>e.type==='jump').length,1,'one jump should only produce one jump event');
g.create();settle(g);assert.equal(g.command({type:'Goal',intent:'crossFence'}),true);for(let i=0;i<460&&!g.events.some(e=>e.type==='goal_success');i++)g.step();assert.ok(g.events.some(e=>e.type==='goal_success'),'automatic fence crossing must succeed through real physics');assert.ok(g.state().player.x>S.fenceX+0.8,'physical position must be beyond fence');assert.equal(g.events.filter(e=>e.type==='jump').length,1,'goal must jump once');
const saved=g.snapshot();const h=new GameCore();assert.equal(h.restore(saved),true,'valid snapshot must load');assert.ok(Math.abs(h.state().player.x-g.state().player.x)<1e-4,'restore must preserve position');assert.equal(h.restore({...saved,player:{...saved.player,p:{...saved.player.p,x:Infinity}}}),false,'invalid numeric state must be rejected');
const n=new GameCore();settle(n);n.command({type:'Goal',intent:'crossFence'});n.command({type:'Move',direction:-1});assert.equal(n.goal,null,'manual override must cancel automation');
const c=new GameCore();settle(c);c.player.setTranslation({x:7,y:.86,z:0},true);c.command({type:'Move',direction:1});for(let i=0;i<120;i++)c.step();assert.ok(c.state().crate.x>S.crateX+.1,`crate must be pushed by rigid-body contact: ${c.state().crate.x}`);
console.log(JSON.stringify({passed:true,jumpPeakMeters:peak,goalEndX:g.state().player.x,crateFinalX:c.state().crate.x,tests:['ground','jump','jump count','goal','3D collision','snapshot','invalid state','manual override','crate pushing']}));
const semantic=new GameCore();settle(semantic);assert.equal(semantic.state().visibleEntities.some(e=>e.id==='wanderer-1'),false,'distant wandering actor must stay invisible');const before=semantic.semantic.entities[0].x;for(let i=0;i<180;i++)semantic.step();assert.notEqual(semantic.semantic.entities[0].x,before,'offscreen semantic actor must evolve');semantic.player.setTranslation({x:14,y:1,z:0},true);assert.ok(semantic.state().visibleEntities.length>0,'nearby semantic actor must materialize for adapter');const persistent=semantic.snapshot();const again=new GameCore();assert.equal(again.restore(persistent),true);assert.equal(again.semantic.entities[0].x,semantic.semantic.entities[0].x,'semantic state must survive save/load');assert.equal(again.semantic.entities[0].revision,semantic.semantic.entities[0].revision,'semantic revision must persist');console.log('PRSE semantic evolution, visibility and save/load PASSED');
const doll=new GameCore();settle(doll);const dollBefore=doll.state().ragdoll.parts.torso.position.x;assert.equal(doll.command({type:'PushRagdoll'}),true);for(let i=0;i<12;i++)doll.step();assert.ok(Math.abs(doll.state().ragdoll.parts.torso.position.x-dollBefore)>.07,'articulated mannequin must respond to force');assert.equal(Object.keys(doll.activeRagdoll.parts).length,10,'ten rigid bodies exist');assert.equal(Object.keys(doll.activeRagdoll.joints).length,9,'nine joints exist');const dollSave=doll.snapshot();const restoredDoll=new GameCore();assert.equal(restoredDoll.restore(dollSave),true);assert.ok(Math.abs(restoredDoll.state().ragdoll.parts.torso.position.x-doll.state().ragdoll.parts.torso.position.x)<.001,'ragdoll state must persist');assert.equal(doll.command({type:'SetRagdollMode',mode:'walk'}),true);assert.equal(doll.command({type:'SetRagdollMode',mode:'invalid'}),false);assert.equal(doll.command({type:'InjureRagdoll',part:'leftKnee',injury:'sprain',severity:.8}),true);assert.equal(doll.command({type:'HealRagdoll'}),true);console.log('ACTIVE RAGDOLL physics, nine motors, command validation, save/load PASSED');

const left=new GameCore();left.command({type:'Move',direction:-1});for(let i=0;i<25;i++)left.step();assert.equal(left.direction,-1,'render adapter must face left with physical leftward motion');console.log('Physics impulse movement and travel-facing direction PASSED');
