#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PACKAGES = ROOT / "unity" / "packages"
OUTPUT = ROOT / "doc" / "dependency-audit-phase1.md"
RELEASE_CONFIG = ROOT / "unity" / "tools" / "release" / "release_packages.json"


def package_paths():
    return sorted([path for path in PACKAGES.iterdir() if path.is_dir() and (path / "package.json").exists()])


def grep_hits(package_path: Path, pattern: str):
    hits = []
    for file_path in sorted(package_path.rglob("*")):
        if file_path.is_dir():
            continue
        if file_path.suffix not in {".cs", ".md", ".json", ".asmdef", ".txt"} and file_path.name not in {"package.json", ".gitignore"}:
            continue

        for line_number, line in enumerate(file_path.read_text(encoding="utf-8").splitlines(), start=1):
            if pattern in line:
                hits.append((file_path.relative_to(ROOT), line_number, line.strip()))
    return hits


def main():
    release_config = json.loads(RELEASE_CONFIG.read_text())
    forbidden_patterns = release_config["forbidden_patterns"]
    sellable_packages = {entry["name"] for entry in release_config["sellable_packages"]}

    lines = ["# Phase 1 Dependency Audit", "", "Generated by `unity/tools/architecture/dependency_audit.py`.", ""]
    lines.append("## Package graph")
    lines.append("")
    for package_path in package_paths():
        data = json.loads((package_path / "package.json").read_text())
        deps = sorted((data.get("dependencies") or {}).keys())
        lines.append(f"- `{data['name']}`")
        if deps:
            for dep in deps:
                lines.append(f"  - depends on `{dep}`")
        else:
            lines.append("  - depends on no local packages")
    lines.append("")
    lines.append("## Violations and extraction markers")
    lines.append("")
    failures = []

    for package_path in package_paths():
        data = json.loads((package_path / "package.json").read_text())
        lines.append(f"### `{data['name']}`")
        any_hits = False
        package_hits = []
        for label, pattern in forbidden_patterns.items():
            hits = grep_hits(package_path, pattern)
            if not hits:
                continue
            any_hits = True
            lines.append(f"- {label}:")
            for relative_path, line_number, snippet in hits:
                lines.append(f"  - `{relative_path}:{line_number}` `{snippet}`")
                package_hits.append((label, relative_path, line_number))
        if not any_hits:
            lines.append("- no phase-1 forbidden references found")
        elif data["name"] in sellable_packages:
            failures.append(
                f"{data['name']}: forbidden references remain in a sellable package"
            )
        lines.append("")

    lines.append("## Result")
    if failures:
        lines.append("- FAILED")
        lines.extend(f"- {failure}" for failure in failures)
    else:
        lines.append("- PASSED")
        lines.append("- no forbidden references remain in the designated sellable packages")

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT}")
    if failures:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
