#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PACKAGES = ROOT / "unity" / "packages"
OUTPUT = ROOT / "doc" / "dependency-audit-phase1.md"

FORBIDDEN_PATTERNS = {
    "GameManager reference": "GameManager",
    "SceneBootstrap reference": "SceneBootstrap",
    "Direct scene search": "FindAnyObjectByType",
    "Parent MonoBehaviour lookup": "GetComponentsInParent<MonoBehaviour>(true).FirstOrDefault",
}


def package_paths():
    return sorted([path for path in PACKAGES.iterdir() if path.is_dir() and (path / "package.json").exists()])


def grep_hits(package_path: Path, pattern: str):
    hits = []
    for file_path in sorted(package_path.rglob("*.cs")):
        for line_number, line in enumerate(file_path.read_text().splitlines(), start=1):
            if pattern in line:
                hits.append((file_path.relative_to(ROOT), line_number, line.strip()))
    return hits


def main():
    lines = ["# Phase 1 Dependency Audit", "", "Generated by `unity/tools/architecture/dependency_audit.py`.", ""]
    lines.append("## Package graph")
    lines.append("")
    for package_path in package_paths():
        data = json.loads((package_path / "package.json").read_text())
        deps = sorted((data.get("dependencies") or {}).keys())
        lines.append(f"- `{data['name']}`")
        if deps:
            for dep in deps:
                lines.append(f"  - depends on `{dep}`")
        else:
            lines.append("  - depends on no local packages")
    lines.append("")
    lines.append("## Violations and extraction markers")
    lines.append("")

    for package_path in package_paths():
        data = json.loads((package_path / "package.json").read_text())
        lines.append(f"### `{data['name']}`")
        any_hits = False
        for label, pattern in FORBIDDEN_PATTERNS.items():
            hits = grep_hits(package_path, pattern)
            if not hits:
                continue
            any_hits = True
            lines.append(f"- {label}:")
            for relative_path, line_number, snippet in hits:
                lines.append(f"  - `{relative_path}:{line_number}` `{snippet}`")
        if not any_hits:
            lines.append("- no phase-1 forbidden references found")
        lines.append("")

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
