import assert from 'node:assert/strict';
import {initializePhysics,GameCore} from '../physics-core.js';
import {WorldConsequences}from '../world-consequences.js';
await initializePhysics();
const step=(g,n)=>{for(let i=0;i<n;i++)g.step();};
const locate=(g,x)=>{g.player.setTranslation({x,y:.86,z:0},true);g.player.setLinvel({x:0,y:0,z:0},true);step(g,5);};
const atShelter=()=>{const g=new GameCore();locate(g,37.1);return g;};
const g=atShelter();assert.ok(g.worldBridge.active.has('shelter-candle'));
const candle=g.semantic.entity('shelter-candle'),note=g.semantic.entity('shelter-note');
assert.equal(g.command({type:'Interact',targetId:'shelter-note',verb:'ignite'}),false,'paper must not ignite from unlit candle');
assert.equal(note.state.condition,'intact');
assert.equal(g.command({type:'Interact',targetId:'shelter-candle',verb:'light'}),true);
assert.equal(candle.state.lit,true);
assert.equal(g.command({type:'Interact',targetId:'shelter-note',verb:'ignite'}),true);
assert.equal(g.consequences.pending.length,7);
const saveDuring=g.snapshot(),loaded=new GameCore();assert.equal(loaded.restore(saveDuring),true,'save during ongoing ignition');
assert.deepEqual(loaded.consequences.snapshot(),g.consequences.snapshot(),'queued story transitions survive save/load');
locate(g,26);locate(loaded,26);step(g,2500);step(loaded,2500);
assert.equal(g.semantic.entity('shelter-note').state.condition,'ashes');
assert.equal(g.semantic.entity('shelter-bench').state.condition,'scorched');
assert.equal(g.semantic.entity('shelter-setting').state.condition,'smoky');
assert.equal(loaded.semantic.entity('shelter-note').state.condition,g.semantic.entity('shelter-note').state.condition);
assert.equal(g.consequences.pending.length,0);
assert.ok(g.events.some(e=>e.type==='paper_burning'&&e.visibility==='offscreen'),'offscreen fire recorded without telling distant player');
locate(g,35);const discovery=g.events.filter(e=>e.type==='scene_discovered');assert.ok(discovery.length,'returning player must discover consequences');
assert.ok(discovery.at(-1).message.includes('Soot'),'physical scene should reveal changed narrative facts');
assert.equal(g.worldBridge.active.has('shelter-note'),true,'ash description persists as a materialized identity');
// Distinguish preventing destruction using an actual nearby water source.
const spared=atShelter();assert.equal(spared.command({type:'Interact',targetId:'shelter-candle',verb:'light'}),true);
assert.equal(spared.command({type:'Interact',targetId:'shelter-note',verb:'ignite'}),true);step(spared,450);
locate(spared,37.6);assert.equal(spared.command({type:'Interact',targetId:'shelter-jug',verb:'pour'}),true);
assert.equal(spared.semantic.entity('shelter-note').state.condition,'wet');assert.equal(spared.consequences.pending.length,0);
const waterSave=spared.snapshot(),restoreWater=new GameCore();assert.ok(restoreWater.restore(waterSave));
step(restoreWater,2200);assert.equal(restoreWater.semantic.entity('shelter-note').state.condition,'wet');assert.notEqual(restoreWater.semantic.entity('shelter-bench').state.condition,'burning');
assert.equal(restoreWater.command({type:'Interact',targetId:'shelter-jug',verb:'pour'}),false,'water cannot be reused');
assert.equal(g.command({type:'Interact',targetId:'shelter-candle',verb:'light'}),false,'faraway candle cannot be lit');
const c=new WorldConsequences();const invalid=structuredClone(c.snapshot());invalid.pending=[{time:-1,type:'paper_burning',entity:'shelter-note',condition:'burning',message:'bad',episode:1}];assert.equal(c.restore(invalid),false);
console.log(JSON.stringify({passed:true,litWithoutFlameBlocked:true,fireStages:g.consequences.history.map(e=>e.type),offscreenEvents:g.events.filter(e=>e.visibility==='offscreen').length,returnedDiscovery:discovery.at(-1).message,wetAfterRescue:restoreWater.semantic.entity('shelter-note').state.condition}));
